using Upkeep.App.Core.Elevation;

namespace Upkeep.App.Core.Tests.Elevation;

public class HelperStartupArgumentsTests
{
    private static string[] Arguments(string pipeName, string parentProcessId) =>
        ["--elevated-helper", HelperStartupArguments.PipeArgument, pipeName, HelperStartupArguments.ParentArgument, parentProcessId];

    [Fact]
    public void TryParse_WellFormedArguments_Succeeds()
    {
        bool parsed = HelperStartupArguments.TryParse(Arguments("upkeepabc123def456", "4242"), out var startup, out string? error);

        Assert.True(parsed);
        Assert.Null(error);
        Assert.Equal("upkeepabc123def456", startup.PipeName);
        Assert.Equal(4242, startup.ParentProcessId);
    }

    [Theory]
    [InlineData("short")]
    [InlineData("has-a-dash-in-it-here")]
    [InlineData("has a space in it here")]
    [InlineData("..\\..\\pipe\\something")]
    public void TryParse_PipeNameOutsideTheGeneratedShape_IsRejected(string pipeName)
    {
        // The name is generated by the shell and only ever used as a name; anything that isn't the
        // shape we generate is refused rather than passed through to Windows.
        bool parsed = HelperStartupArguments.TryParse(Arguments(pipeName, "4242"), out _, out string? error);

        Assert.False(parsed);
        Assert.NotNull(error);
    }

    [Fact]
    public void TryParse_MissingParentProcessId_IsRejected()
    {
        bool parsed = HelperStartupArguments.TryParse(["--elevated-helper", HelperStartupArguments.PipeArgument, "upkeepabc123def456"], out _, out string? error);

        Assert.False(parsed);
        Assert.NotNull(error);
    }

    [Theory]
    [InlineData("0")]
    [InlineData("-1")]
    [InlineData("not-a-number")]
    public void TryParse_UnusableParentProcessId_IsRejected(string parentProcessId)
    {
        bool parsed = HelperStartupArguments.TryParse(Arguments("upkeepabc123def456", parentProcessId), out _, out string? error);

        Assert.False(parsed);
        Assert.NotNull(error);
    }

    [Fact]
    public void TryParse_NoArgumentsAtAll_IsRejected()
    {
        bool parsed = HelperStartupArguments.TryParse([], out _, out string? error);

        Assert.False(parsed);
        Assert.NotNull(error);
    }
}
